"""Who-is-centered bucket assignments, hand-coded by reading the 'Who is
centered' field for Engineering/Safety and Equity, and inferred from Central
claim/Relevance to argument for Participatory Method and Food Justice
(neither has a Who is centered column at all, noted in the report)."""

ENG = "Engineering/Safety"
EQ = "Equity"
PM = "Participatory Method"
FJ = "Food Justice"

WHO_CENTERED = {
    (ENG, "Hicks, D., Kingsley, G., & Isett, K.R.", 2025): "Regulators/officials",
    (ENG, "London, A.J. & Danks, D.", 2018): "Regulators/officials",
    (ENG, "Robles, P. & Mallinson, D.J.", 2024): "Regulators/officials",
    (ENG, "Alkurdi, D. & Alsaid, A.", 2025): "Researchers synthesizing literature",
    (ENG, "Lee, J.D. & Kolodge, K.", 2020): "Engineers/technical experts",
    (ENG, "Kraus, J., Scholz, D., Stiegemeier, D., & Baumann, M.", 2020): "Engineers/technical experts",
    (ENG, "Zhang, B., de Winter, J., Varotto, S., Happee, R., & Martens, M.", 2019): "Researchers synthesizing literature",
    (ENG, "Peng, Q., Wu, Y., Qie, N., & Iwaki, S.", 2022): "Engineers/technical experts",
    (ENG, "Pedroff, J.", 2025): "Researchers synthesizing literature",
    (ENG, "Lee, M.B., Lee, C.T., Abas, M.A., & Chong, W.W.F.", 2025): "Researchers synthesizing literature",
    (ENG, "Kooijman, L., Happee, R., & de Winter, J.C.F.", 2019): "Engineers/technical experts",
    (ENG, "Pimenta, A.R., Kamruzzaman, M., & Currie, G.", 2023): "Regulators/officials",
    (ENG, "Park, J., Jang, S., & Ko, J.", 2024): "Engineers/technical experts",
    (ENG, "Lu, Q., Tettamanti, T., Hörcher, D., & Varga, I.", 2020): "Engineers/technical experts",
    (ENG, "Palatinus, Z., Volosin, M., Csabi, E., Hallgato, E., Hajnal, E., Lukovics, M., Pronay, S., Ujhazi, T., Osztobanyi, L., Szabo, B., Kralik, T., & Majo-Petri, Z.", 2022): "Engineers/technical experts",
    (ENG, "Zoellick, J.C., Kuhlmey, A., Schenk, L., Schindel, D., & Bluher, S.", 2019): "Engineers/technical experts",
    (ENG, "Nordhoff, S., Stapel, J., van Arem, B., & Happee, R.", 2020): "Engineers/technical experts",

    (EQ, "Levine", 2024): "Community members/residents",
    (EQ, "Zhang et al.", 2024): "Researchers synthesizing literature",
    (EQ, "Pinski et al.", 2024): "Community members/residents",
    (EQ, "Agrawaal et al.", 2024): "Advocates/CBOs",
    (EQ, "Gomes et al.", 2026): "Community members/residents",
    (EQ, "Bailey et al.", 2010): "Regulators/officials",
    (EQ, "Soliz et al.", 2026): "Community members/residents",
    (EQ, "McCullough et al.", 2024): "Regulators/officials",
    (EQ, "Chen et al.", 2025): "Regulators/officials",
    (EQ, "Golub et al.", 2013): "Community members/residents",
    (EQ, "McCullogh et al.", 2026): "Researchers synthesizing literature",
    (EQ, "Twardzik et al.", 2025): "Community members/residents",
    (EQ, "Johnson et al.", 2025): "Researchers synthesizing literature",
    (EQ, "Johnson et al.", 2024): "Community members/residents",
    (EQ, "Karner et al.", 2017): "Community members/residents",
    (EQ, "Mottee et al.", 2020): "Regulators/officials",
    (EQ, "Klaever et al.", 2025): "Community members/residents",
    (EQ, "Pineo et al.", 2026): "Regulators/officials",
    (EQ, "Di Ruocco", 2025): "Researchers synthesizing literature",
    (EQ, "Jensen", 2026): "Community members/residents",
    (EQ, "van Holstein et al.", 2020): "Advocates/CBOs",
    (EQ, "Jeghers et al.", 2024): "Regulators/officials",
    (EQ, "Yin et al.", 2026): "Community members/residents",
    (EQ, "Contreras et al.", 2026): "Advocates/CBOs",
    (EQ, "Bailey et al.", 2012): "Community members/residents",
    (EQ, "Chapman et al.", 2024): "Community members/residents",
    (EQ, "Bahman et al.", 2026): "Researchers synthesizing literature",
    (EQ, "Nakshi et al.", 2025): "Community members/residents",
    (EQ, "Linovski et al.", 2026): "Regulators/officials",
    (EQ, "Zhang et al.", 2025): "Community members/residents",
    (EQ, "Wander et al.", 2026): "Community members/residents",
    (EQ, "Mouratidis", 2026): "Researchers synthesizing literature",
    (EQ, "Situ", 2025): "Community members/residents",
    (EQ, "Karner et al.", 2020): "Advocates/CBOs",
    (EQ, "Cha et al.", 2020): "Community members/residents",
    (EQ, "Pan et al.", 2024): "Researchers synthesizing literature",
    (EQ, "Vanderschuren et al.", 2021): "Community members/residents",
    (EQ, "Sutcliffe et al.", 2021): "Regulators/officials",
    (EQ, "Grasso et al.", 2020): "Community members/residents",

    (PM, "Baumann, K., Caldwell, B., Bar, F., & Stokes, B.", 2018): "Community members/residents",
    (PM, "Van Wynsberghe, A., & Guimarães Pereira, Â.", 2022): "Community members/residents",
    (PM, "Severs, R., Wu, J., Diels, C., Harrow, D., Singleton, J., & Winsor, R.", 2022): "Community members/residents",
    (PM, "Tan, Y., Soh, K.X., Zhang, R., Lee, J., Meng, H., Sen, B., & Lee, Y.-C.", 2025): "Frontline practitioners",
    (PM, "Aranda-Muñoz, Á., Bozic Yams, N., & Carlgren, L.", 2025): "Frontline practitioners",
    (PM, "Liao, Q.V., & Muller, M.", 2019): "Researchers synthesizing literature",
    (PM, "Barendregt, L., Bendor, R., & van Eekelen, B.F.", 2024): "Researchers synthesizing literature",
    (PM, "Forlano, L., & Mathew, A.", 2014): "Regulators/officials",
    (PM, "Omori, M., & Lim, Y.", 2025): "Engineers/technical experts",
    (PM, "Sörries, P., Leimstädtner, D., & Müller-Birn, C.", 2024): "Community members/residents",
    (PM, "Wong, R.Y., Mulligan, D.K., Van Wyk, E., Pierce, J., & Chuang, J.", 2017): "Engineers/technical experts",

    (FJ, "Lindemann", 2026): "Community members/residents",
    (FJ, "Gripper", 2022): "Researchers synthesizing literature",
    (FJ, "Murray", 2023): "Researchers synthesizing literature",
    (FJ, "Cresswell Riol", 2023): "Researchers synthesizing literature",
    (FJ, "Engelbutzeder", 2023): "Community members/residents",
    (FJ, "Talhouk", 2022): "Community members/residents",
    (FJ, "Joassart-Marcelli", 2026): "Researchers synthesizing literature",
    (FJ, "Deener", 2017): "Researchers synthesizing literature",
    (FJ, "Shaker", 2023): "Researchers synthesizing literature",
    (FJ, "Prost", 2018): "Community members/residents",
    (FJ, "Cresswell Riol", 2025): "Researchers synthesizing literature",
    (FJ, "Brenton", 2025): "Community members/residents",
    (FJ, "Boling", 2023): "Researchers synthesizing literature",
    (FJ, "Heitlinger", 2021): "Community members/residents",
    (FJ, "Reese", 2019): "Community members/residents",
}
